spring.application.name=smartchain
spring.datasource.url=jdbc:postgresql://localhost:5432/smartchain
spring.datasource.username=postgres
spring.datasource.password=rama

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true