spring.application.name=smartchain
spring.datasource.url=jdbc:postgresql://localhost:5432/smartchain
spring.datasource.username=postgres
spring.datasource.password=rama

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT settings
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=36000000
